name: holiday_aggregator_24
description: The Website for the Holiday Aggregator 24.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_riverpod: ^2.1.1
  freezed_annotation: ^2.2.0
  http: ^0.13.5
  rxdart: ^0.27.7
  provider: ^6.0.4
  get_it: ^7.2.0
  auto_route: ^5.0.2
  rx_cubit: ^0.0.1
  firebase_core: ^2.3.0
  json_annotation: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  auto_route_generator: ^5.0.3

flutter:
  uses-material-design: true
